apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  cluster.initial_master_nodes: "elasticsearch-0,elasticsearch-1"
  discovery.seed_hosts: "elasticsearch-0.es.default.svc.cluster.local,elasticsearch-1.es.default.svc.cluster.local"
  bootstrap.memory_lock: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-config
data:
  REDIS_SLAVE_HOST: "redis-slave"
  REDIS_MASTER_HOST: "redis-master"
  KUBERNETES_SERVICE_HOST: ""
  KUBERNETES_SERVICE_PORT: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-slave-config
data:
  REDIS_MASTER_HOST: "redis-master-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-shared-config
data:
  ELASTICSEARCH_HOSTS: "http://elasticsearch-0.es.default.svc.cluster.local:9200"