apiVersion: v1
kind: Namespace
metadata:
  name: kibana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-shared-config
  namespace: kibana
data:
  ELASTICSEARCH_HOSTS: "http://elasticsearch-0.es.elastic.svc.cluster.local:9200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.1.1
        ports:
        - containerPort: 5601
        env:
        # - name: ELASTICSEARCH_HOSTS
        #   value: "http://elasticsearch-0.es.default.svc.cluster.local:9200"
        - name: SERVER_BASEPATH
          value: "/kibana"
        - name: SERVER_REWRITEBASEPATH
          value: "true"
        envFrom:
        - configMapRef:
            name: app-shared-config
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: kibana
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5601
  selector:
    app: kibana
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: kibana
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana-service
            port:
              number: 80